### ISSUE TITLE
dmlwriteexception when using admin/tool/replace

### ISSUE THREAD

**Issue by ewallah** [e-lang/moodle-mod_elang#67]
Default exception handler: Error writing to database Debug: ERROR:  syntax error at or near "user"
LINE 2:                        SET user = REPLACE(user, $1, $2)
                                   ^
UPDATE mdl_elang_check
                       SET user = REPLACE(user, $1, $2)
                     WHERE user IS NOT NULL
[array (
  0 => 'http://worldbank.',
  1 => 'https://worldbank.',
)]

Error code: dmlwriteexception
* line 489 of /lib/dml/moodle_database.php: dml_write_exception thrown
* line 242 of /lib/dml/pgsql_native_moodle_database.php: call to moodle_database->query_end()
* line 700 of /lib/dml/pgsql_native_moodle_database.php: call to pgsql_native_moodle_database->query_end()
* line 2394 of /lib/dml/moodle_database.php: call to pgsql_native_moodle_database->execute()
* line 8398 of /lib/adminlib.php: call to moodle_database->replace_all_text()
* line 88 of /admin/tool/replace/cli/replace.php: call to db_replace()

!!! Error writing to database !!!

Moodle 3.3
Database: PostgreSQL

**Comment by scara** [comment]
Hi @ewallah,
not sure if this could be an issue of this specific module or a general problem with the Replace Admin Tool in Moodle: did you already post the same issue in the Moodle Community e.g. https://moodle.org/mod/forum/view.php?id=50 or, better, https://moodle.org/mod/forum/view.php?id=55?
Please, refer to this issue here in github.

The issue here IMHO is that `user` is reserved in PostgreSQL (and SQL-92, https://www.postgresql.org/docs/current/static/sql-keywords-appendix.html) and should be renamed (module) or quoted (core code, by properly overriding `moodle_database::replace_all_text()` to quote the reserved words in pg).

HTH,
Matteo

**Comment by scara** [comment]
For future reference: https://moodle.org/mod/forum/discuss.php?d=354485.

HTH,
Matteo

**Comment by chdemko** [comment]
Thanks for the input. Will have a look next autumn

**Comment by scara** [comment]
FYI: https://tracker.moodle.org/browse/MDL-59635.

HTH,
Matteo
