### ISSUE TITLE
Unable to install in Moodle 3.5.1+

### ISSUE THREAD

**Issue by germanvaleroelizondo** [e-lang/moodle-mod_elang#68]
When attempting to install in a brand new local Moodle 3.5.1+ (Build: 20180831) installed with complete Windows install package,  with no additional plugins, and the es_mx language pack, I got this error message:

Install plugins from the Moodle plugins directory

Debugging output enabled
Downloading mod_elang ... 
 <- https://moodle.org/plugins/download.php/17771/mod_elang_moodle35_2018090502.zip
 -> C:\M\m351plus3\server\moodledata/temp/core_plugin/code_manager/distfiles/7a97e85d28c6d79c1ec67cfdc8f40bf4.zip ... OK
Validating mod_elang ... 

core_plugin/corrupted_archive_structure

More information about this error

    

    Debug info: Can not write target file

Error code: corrupted_archive_structure

$a contents: elang/vendor/phpunit/php-code-coverage/tests/_files/Report/XML/CoverageForClassWithAnonymousFunction/source_with_class_and_anonymous_function.php.xml

    

    Stack trace: 

    line 544 of \lib\classes\update\code_manager.php: moodle_exception thrown
    line 195 of \lib\classes\update\code_manager.php: call to core\update\code_manager->move_extracted_plugin_files()
    line 1088 of \lib\classes\plugin_manager.php: call to core\update\code_manager->unzip_plugin_file()
    line 1276 of \lib\classes\plugin_manager.php: call to core_plugin_manager->unzip_plugin_file()
    line 2429 of \lib\upgradelib.php: call to core_plugin_manager->install_plugins()
    line 62 of \admin\tool\installaddon\index.php: call to upgrade_install_plugins()

**Comment by chdemko** [comment]
I don't have this error. Could you try to place the elang folder (inside the zip file) directly into the mod folder of your moodle structure and log in as an admin?

**Comment by gvalero2013** [comment]
Indeed, if I place the elang folder (from inside the ZIP) in the moodle/mod folder, the plugin installs OK. The problem only happens when trying to INSTALL directly from the Moodle plugins database page, which is a very common way to try to install Moodle plugins nowaday.

When you uploaded the plugin into the Moodle plugins database, Did you check the checkboxes that fix the plugin structure (the one that says that is specially useful for plugins hosted in Github?

I recall that there were a few checkboxes that I wasn't quite sure whether my plugins needed them.

Can you please add another version of your plugin, and this time do check these checkboxes and then try to INSTALL directly from the Moodle plugins database. If you mark a new version as NOT VISIBLE, only you can access the INSTALL button for it.

If the above experiment succeeds, you can make visible the new version and hide the former version.

**Comment by chdemko** [comment]
I've published a new release without errors. Let's me know if it's ok

**Comment by gvalero2013** [comment]
The new release installs directly from the Moodle plugins database page without errors.

Thanks for the new release.
